export { SlideProvider, useSlides } from './context/SlideContext.jsx'
export { default as Slide } from './components/Slide.jsx'
export { default as Navigation } from './components/Navigation.jsx'
export { default as BottomBar } from './components/BottomBar.jsx'
export { default as GenericThankYouSlide } from './slides/GenericThankYouSlide.jsx'
export { default as GenericTwoOptionsSlide } from './slides/GenericTwoOptionsSlide.jsx'
export { default as GenericStepsSlide } from './slides/GenericStepsSlide.jsx'
export { default as GenericAgendaSlide } from './slides/GenericAgendaSlide.jsx'
export { default as GenericObjectiveSlide } from './slides/GenericObjectiveSlide.jsx'
export { default as GenericTocSlide } from './slides/GenericTocSlide.jsx'
export { default as GenericGoalsSlide } from './slides/GenericGoalsSlide.jsx'
